name: Check pull request source branch
on:
    pull_request_target:
        types:
            - opened
            - reopened
            - synchronize
            - edited
jobs:
    check-branches:
        if: github.repository == 'elizaOS/eliza' && (github.event_name != 'pull_request_target' || github.event.pull_request.head.repo.full_name == 'elizaOS/eliza')
        runs-on: ubuntu-latest
        steps:
            - name: Check branches
              run: |
                  if [ ${{ github.head_ref }} != "develop" ] && [ ${{ github.base_ref }} == "main" ]; then
                    echo "Merge requests to main branch are only allowed from dev branch."
                    exit 1
                  fi
